export type RecipeCategory = '和食' | '洋食' | '中華'

export type RecipeIngredient = {
  ingredientId: string
  name: string
  amount: number
  unit: string
}

export type Recipe = {
  id: string
  name: string
  category: RecipeCategory
  cookingTime: number
  baseServings: number
  mainIngredients: string[]
  ingredients: RecipeIngredient[]
  steps: string[]
  imageId: string
}

export function getRecipeImageUrl(id: string, width = 400, height = 280): string {
  return `https://images.unsplash.com/photo-${id}?w=${width}&h=${height}&fit=crop&q=80`
}

export const RECIPES: Recipe[] = [
  // ===== 和食 =====
  {
    id: 'nikujaga',
    name: '肉じゃが',
    category: '和食',
    cookingTime: 30,
    baseServings: 4,
    mainIngredients: ['beef', 'potato', 'onion', 'carrot'],
    ingredients: [
      { ingredientId: 'beef', name: '牛肉（薄切り）', amount: 200, unit: 'g' },
      { ingredientId: 'potato', name: 'じゃがいも', amount: 3, unit: '個' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 1, unit: '個' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 1, unit: '本' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 3, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 3, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 2, unit: '大さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 2, unit: '大さじ' },
    ],
    steps: [
      '牛肉は一口大に切る。じゃがいも・にんじんは乱切り、玉ねぎはくし切りにする。',
      '鍋に油を熱し、牛肉を炒める。色が変わったら玉ねぎを加えてさらに炒める。',
      'じゃがいもとにんじんを加え、水300mlと調味料を加えて中火で煮る。',
      'アクを取りながら15〜20分、じゃがいもに火が通るまで煮れば完成。',
    ],
    imageId: '1547592180-85f173990554',
  },
  {
    id: 'shogayaki',
    name: '豚の生姜焼き',
    category: '和食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['pork-loin', 'ginger', 'onion'],
    ingredients: [
      { ingredientId: 'pork-loin', name: '豚ロース', amount: 200, unit: 'g' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 1, unit: '個' },
      { ingredientId: 'ginger', name: '生姜（すりおろし）', amount: 1, unit: '片' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 2, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 2, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 1, unit: '大さじ' },
    ],
    steps: [
      '豚肉は筋切りをして、醤油・みりん・酒・生姜を混ぜたたれに10分漬ける。',
      '玉ねぎは繊維に沿って薄切りにする。',
      'フライパンに油を熱し、玉ねぎを炒めて端に寄せ、豚肉をたれごと焼く。',
      '両面に焼き色がついたら、玉ねぎと合わせて炒め合わせれば完成。',
    ],
    imageId: '1567620832903-9fc6debc209f',
  },
  {
    id: 'karaage',
    name: '鶏のから揚げ',
    category: '和食',
    cookingTime: 25,
    baseServings: 2,
    mainIngredients: ['chicken-thigh', 'ginger', 'garlic'],
    ingredients: [
      { ingredientId: 'chicken-thigh', name: '鶏もも肉', amount: 300, unit: 'g' },
      { ingredientId: 'ginger', name: '生姜（すりおろし）', amount: 1, unit: '片' },
      { ingredientId: 'garlic', name: 'にんにく（すりおろし）', amount: 1, unit: '片' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 2, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 1, unit: '大さじ' },
      { ingredientId: 'starch', name: '片栗粉', amount: 4, unit: '大さじ' },
    ],
    steps: [
      '鶏肉は一口大に切り、醤油・酒・生姜・にんにくで20分漬け込む。',
      '片栗粉をまぶし、170℃の油で4分揚げる。',
      'いったん取り出して油を切り、180℃で1分二度揚げすれば完成。',
    ],
    imageId: '1626200419199-391ae4be7a41',
  },
  {
    id: 'oyakodon',
    name: '親子丼',
    category: '和食',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['chicken-thigh', 'egg', 'onion'],
    ingredients: [
      { ingredientId: 'chicken-thigh', name: '鶏もも肉', amount: 200, unit: 'g' },
      { ingredientId: 'egg', name: '卵', amount: 3, unit: '個' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 1, unit: '個' },
      { ingredientId: 'rice', name: 'ごはん', amount: 2, unit: '膳分' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 2, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 2, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 2, unit: '大さじ' },
      { ingredientId: 'dashi', name: 'だし', amount: 200, unit: 'ml' },
    ],
    steps: [
      '鶏肉は一口大に、玉ねぎは薄切りにする。',
      '小鍋にだし・醤油・みりん・酒を入れ、玉ねぎと鶏肉を煮る。',
      '鶏肉に火が通ったら卵（溶き卵）を回し入れ、半熟になったら火を止める。',
      'ごはんにのせれば完成。',
    ],
    imageId: '1546069901-ba9599a7e63c',
  },
  {
    id: 'tonjiru',
    name: '豚汁',
    category: '和食',
    cookingTime: 25,
    baseServings: 4,
    mainIngredients: ['pork-belly', 'daikon', 'carrot', 'potato', 'miso'],
    ingredients: [
      { ingredientId: 'pork-belly', name: '豚バラ肉', amount: 150, unit: 'g' },
      { ingredientId: 'daikon', name: '大根', amount: 200, unit: 'g' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 1, unit: '本' },
      { ingredientId: 'potato', name: 'じゃがいも', amount: 2, unit: '個' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 1, unit: '本' },
      { ingredientId: 'miso', name: '味噌', amount: 4, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'dashi', name: 'だし', amount: 800, unit: 'ml' },
    ],
    steps: [
      '野菜は食べやすい大きさに切る。豚肉は3cm幅に切る。',
      '鍋でごま油を熱し、豚肉を炒め、野菜を加えてさらに炒める。',
      'だしを加えて中火で15分煮る。',
      '味噌を溶き入れ、ひと煮立ちしたら完成。',
    ],
    imageId: '1525059696034-4967a8e1dca2',
  },
  {
    id: 'misoshiru',
    name: '味噌汁',
    category: '和食',
    cookingTime: 10,
    baseServings: 2,
    mainIngredients: ['miso', 'tofu', 'wakame'],
    ingredients: [
      { ingredientId: 'tofu', name: '豆腐', amount: 150, unit: 'g' },
      { ingredientId: 'wakame', name: 'わかめ', amount: 5, unit: 'g' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 0.3, unit: '本' },
      { ingredientId: 'miso', name: '味噌', amount: 2, unit: '大さじ' },
      { ingredientId: 'dashi', name: 'だし', amount: 400, unit: 'ml' },
    ],
    steps: [
      'だしを沸かし、豆腐（さいの目切り）とわかめを入れる。',
      '味噌を溶き入れ、ひと煮立ちしたら長ねぎを加えて完成。',
    ],
    imageId: '1525059696034-4967a8e1dca2',
  },
  {
    id: 'salmon-shio',
    name: '鮭の塩焼き',
    category: '和食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['salmon'],
    ingredients: [
      { ingredientId: 'salmon', name: '鮭', amount: 2, unit: '切れ' },
      { ingredientId: 'salt', name: '塩', amount: 1, unit: '小さじ' },
      { ingredientId: 'lemon', name: 'レモン', amount: 0.5, unit: '個' },
    ],
    steps: [
      '鮭に塩をふり、10分置いて水気を拭く。',
      'グリルまたはフライパンで両面を焼く（中火で片面4〜5分）。',
      '器に盛り、レモンを添えれば完成。',
    ],
    imageId: '1467003909585-2f8a72700288',
  },
  {
    id: 'saba-miso',
    name: 'サバの味噌煮',
    category: '和食',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['mackerel', 'miso', 'ginger'],
    ingredients: [
      { ingredientId: 'mackerel', name: 'サバ', amount: 2, unit: '切れ' },
      { ingredientId: 'ginger', name: '生姜', amount: 1, unit: '片' },
      { ingredientId: 'miso', name: '味噌', amount: 2, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 2, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 2, unit: '大さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 1, unit: '大さじ' },
    ],
    steps: [
      'サバに熱湯をかけて臭みを取り、水気を拭く。',
      'フライパンに水200ml・酒・砂糖・みりんを入れて煮立て、サバと生姜を入れる。',
      '落とし蓋をして5分煮たら、味噌を加えてさらに5分煮て完成。',
    ],
    imageId: '1534482421-64566f976cfa',
  },
  {
    id: 'tamagoyaki',
    name: '玉子焼き',
    category: '和食',
    cookingTime: 10,
    baseServings: 2,
    mainIngredients: ['egg'],
    ingredients: [
      { ingredientId: 'egg', name: '卵', amount: 3, unit: '個' },
      { ingredientId: 'dashi', name: 'だし', amount: 30, unit: 'ml' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 0.5, unit: '小さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 1, unit: '小さじ' },
    ],
    steps: [
      '卵を溶き、だし・醤油・砂糖を加えて混ぜる。',
      '卵焼き器に油を熱し、卵液を3回に分けて流し入れながら巻いていく。',
      '形を整えて冷めたら、食べやすい大きさに切って完成。',
    ],
    imageId: '1529692236671-f1f6cf9683ba',
  },
  {
    id: 'kinpira',
    name: 'きんぴらごぼう',
    category: '和食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['burdock', 'carrot'],
    ingredients: [
      { ingredientId: 'burdock', name: 'ごぼう', amount: 1, unit: '本' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 0.5, unit: '本' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 1, unit: '大さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 1, unit: '小さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'sesame', name: 'ごま', amount: 1, unit: '小さじ' },
    ],
    steps: [
      'ごぼうは細切り（ささがきでも可）にして水にさらす。にんじんも細切りにする。',
      'フライパンにごま油を熱し、水気を切ったごぼうとにんじんを炒める。',
      '醤油・みりん・酒・砂糖を加えて、汁気がなくなるまで炒め煮する。',
      'ごまを振って完成。',
    ],
    imageId: '1512621776951-a57141f2eefd',
  },
  {
    id: 'kabocha-nimono',
    name: 'かぼちゃの煮物',
    category: '和食',
    cookingTime: 20,
    baseServings: 4,
    mainIngredients: ['pumpkin'],
    ingredients: [
      { ingredientId: 'pumpkin', name: 'かぼちゃ', amount: 400, unit: 'g' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 2, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 2, unit: '大さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 1, unit: '大さじ' },
      { ingredientId: 'dashi', name: 'だし', amount: 200, unit: 'ml' },
    ],
    steps: [
      'かぼちゃは一口大に切り、皮をところどころむく。',
      '鍋にだし・醤油・みりん・砂糖を入れて煮立て、かぼちゃを加える。',
      '落とし蓋をして弱火で15分煮れば完成。',
    ],
    imageId: '1574071318508-1cdbab80d002',
  },
  {
    id: 'daikon-nimono',
    name: '大根の煮物',
    category: '和食',
    cookingTime: 30,
    baseServings: 4,
    mainIngredients: ['daikon'],
    ingredients: [
      { ingredientId: 'daikon', name: '大根', amount: 500, unit: 'g' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 3, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 2, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 2, unit: '大さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 1, unit: '大さじ' },
      { ingredientId: 'dashi', name: 'だし', amount: 400, unit: 'ml' },
    ],
    steps: [
      '大根は3cm厚さの輪切りにし、面取りをして十字の隠し包丁を入れる。',
      '下茹でして水にさらす。',
      'だし・調味料と一緒に弱火で20分煮れば完成。',
    ],
    imageId: '1603360946369-dc9bb6258143',
  },
  {
    id: 'spinach-ohitashi',
    name: 'ほうれん草のお浸し',
    category: '和食',
    cookingTime: 10,
    baseServings: 2,
    mainIngredients: ['spinach'],
    ingredients: [
      { ingredientId: 'spinach', name: 'ほうれん草', amount: 200, unit: 'g' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'dashi', name: 'だし', amount: 50, unit: 'ml' },
      { ingredientId: 'sesame', name: 'ごま', amount: 1, unit: '小さじ' },
    ],
    steps: [
      'ほうれん草を塩茹でし、冷水にとって水気を絞る。',
      '4cm幅に切り、だし・醤油を合わせたものに浸す。',
      'ごまを振って完成。',
    ],
    imageId: '1512621776951-a57141f2eefd',
  },
  {
    id: 'iri-dofu',
    name: '炒り豆腐',
    category: '和食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['tofu', 'egg', 'carrot'],
    ingredients: [
      { ingredientId: 'tofu', name: '木綿豆腐', amount: 1, unit: '丁' },
      { ingredientId: 'egg', name: '卵', amount: 2, unit: '個' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 0.5, unit: '本' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 0.3, unit: '本' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 1, unit: '大さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 0.5, unit: '大さじ' },
    ],
    steps: [
      '豆腐はキッチンペーパーで水気を切る。にんじんは細切りにする。',
      'フライパンに油を熱し、にんじんを炒め、豆腐を崩しながら加える。',
      '調味料を加えて炒め、溶き卵を回し入れてさっと混ぜれば完成。',
    ],
    imageId: '1601050690597-df0568f70950',
  },
  {
    id: 'hijiki-nimono',
    name: 'ひじきの煮物',
    category: '和食',
    cookingTime: 20,
    baseServings: 4,
    mainIngredients: ['hijiki', 'carrot', 'abura-age'],
    ingredients: [
      { ingredientId: 'hijiki', name: 'ひじき（乾燥）', amount: 20, unit: 'g' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 0.5, unit: '本' },
      { ingredientId: 'abura-age', name: '油揚げ', amount: 1, unit: '枚' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 2, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 2, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 1, unit: '大さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 1, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
    ],
    steps: [
      'ひじきは水で戻しておく。油揚げは油抜きして細切りに、にんじんも細切りにする。',
      'フライパンにごま油を熱し、水気を切ったひじき・にんじん・油揚げを炒める。',
      '調味料と水100mlを加え、汁気がなくなるまで煮れば完成。',
    ],
    imageId: '1547592180-85f173990554',
  },
  {
    id: 'tofu-steak',
    name: '豆腐ステーキ',
    category: '和食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['tofu'],
    ingredients: [
      { ingredientId: 'tofu', name: '木綿豆腐', amount: 1, unit: '丁' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 0.3, unit: '本' },
      { ingredientId: 'ginger', name: '生姜', amount: 0.5, unit: '片' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 2, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 1, unit: '大さじ' },
      { ingredientId: 'starch', name: '片栗粉', amount: 2, unit: '大さじ' },
    ],
    steps: [
      '豆腐はキッチンペーパーで水気を取り、2cm厚さに切って片栗粉をまぶす。',
      'フライパンに油を熱し、豆腐を両面こんがり焼く。',
      '醤油・みりんを加えてからめ、ねぎ・生姜をのせて完成。',
    ],
    imageId: '1565557623262-b51c2513a641',
  },
  {
    id: 'nasu-agedashi',
    name: '茄子の揚げ浸し',
    category: '和食',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['eggplant'],
    ingredients: [
      { ingredientId: 'eggplant', name: 'ナス', amount: 3, unit: '本' },
      { ingredientId: 'ginger', name: '生姜', amount: 1, unit: '片' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 2, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 2, unit: '大さじ' },
      { ingredientId: 'dashi', name: 'だし', amount: 200, unit: 'ml' },
    ],
    steps: [
      'ナスは縦半分に切り、皮に斜め格子の切り込みを入れる。',
      '170℃の油で3〜4分揚げる。',
      'だし・醤油・みりんを合わせた漬け汁に熱いうちに浸し、冷めたら盛り付けて完成。',
    ],
    imageId: '1565557623262-b51c2513a641',
  },
  {
    id: 'chahan-jp',
    name: 'チャーハン（和風）',
    category: '和食',
    cookingTime: 10,
    baseServings: 2,
    mainIngredients: ['rice', 'egg', 'ham', 'negi'],
    ingredients: [
      { ingredientId: 'rice', name: 'ごはん', amount: 2, unit: '膳分' },
      { ingredientId: 'egg', name: '卵', amount: 2, unit: '個' },
      { ingredientId: 'ham', name: 'ハム', amount: 3, unit: '枚' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 0.3, unit: '本' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'salt', name: '塩', amount: 0.5, unit: '小さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
    ],
    steps: [
      'ハムは1cm角に切り、ねぎは小口切りにする。',
      'フライパンをよく熱し、溶き卵を入れてすぐごはんを加え、素早く炒める。',
      'ハム・ねぎを加え、醤油・塩・ごま油で味付けして完成。',
    ],
    imageId: '1563379091339-03b21ab4a4f8',
  },
  {
    id: 'saba-can-daikon',
    name: 'サバ缶の大根煮',
    category: '和食',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['mackerel-can', 'daikon'],
    ingredients: [
      { ingredientId: 'mackerel-can', name: 'サバ缶（水煮）', amount: 1, unit: '缶' },
      { ingredientId: 'daikon', name: '大根', amount: 300, unit: 'g' },
      { ingredientId: 'ginger', name: '生姜', amount: 1, unit: '片' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 2, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 2, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 1, unit: '大さじ' },
    ],
    steps: [
      '大根は2cm厚さのいちょう切りにする。',
      '鍋に大根・生姜・だし300mlを入れて中火で10分煮る。',
      'サバ缶を汁ごと加え、醤油・みりん・酒を加えてさらに10分煮れば完成。',
    ],
    imageId: '1534482421-64566f976cfa',
  },
  {
    id: 'atsuage-kinpira',
    name: '厚揚げのきんぴら',
    category: '和食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['atsu-age', 'carrot'],
    ingredients: [
      { ingredientId: 'atsu-age', name: '厚揚げ', amount: 1, unit: '枚' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 0.5, unit: '本' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 0.3, unit: '本' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'mirin', name: 'みりん', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
    ],
    steps: [
      '厚揚げは食べやすい大きさに切る。にんじんは細切りにする。',
      'フライパンにごま油を熱し、にんじんを炒め、厚揚げを加える。',
      '醤油・みりんで炒め煮して、ねぎを加えて完成。',
    ],
    imageId: '1567620905732-2d1ec7ab7445',
  },

  // ===== 洋食 =====
  {
    id: 'hamburger',
    name: 'ハンバーグ',
    category: '洋食',
    cookingTime: 30,
    baseServings: 2,
    mainIngredients: ['ground-mix', 'onion', 'egg'],
    ingredients: [
      { ingredientId: 'ground-mix', name: '合挽き肉', amount: 300, unit: 'g' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 1, unit: '個' },
      { ingredientId: 'egg', name: '卵', amount: 1, unit: '個' },
      { ingredientId: 'breadcrumb', name: 'パン粉', amount: 30, unit: 'g' },
      { ingredientId: 'milk', name: '牛乳', amount: 50, unit: 'ml' },
      { ingredientId: 'salt', name: '塩', amount: 0.5, unit: '小さじ' },
      { ingredientId: 'ketchup', name: 'ケチャップ', amount: 2, unit: '大さじ' },
      { ingredientId: 'worcester', name: 'ウスターソース', amount: 2, unit: '大さじ' },
    ],
    steps: [
      '玉ねぎをみじん切りにして炒め、冷ます。パン粉を牛乳で湿らせる。',
      '合挽き肉・玉ねぎ・卵・パン粉・塩を混ぜてよくこね、楕円形に成形する。',
      'フライパンで両面を焼き、蓋をして蒸し焼き（5分）にする。',
      'ケチャップとウスターソースを合わせたソースをかけて完成。',
    ],
    imageId: '1568901346375-23c9450c58cd',
  },
  {
    id: 'curry',
    name: 'カレーライス',
    category: '洋食',
    cookingTime: 40,
    baseServings: 4,
    mainIngredients: ['chicken-thigh', 'potato', 'onion', 'carrot', 'curry-roux'],
    ingredients: [
      { ingredientId: 'chicken-thigh', name: '鶏もも肉', amount: 300, unit: 'g' },
      { ingredientId: 'potato', name: 'じゃがいも', amount: 3, unit: '個' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 2, unit: '個' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 1, unit: '本' },
      { ingredientId: 'curry-roux', name: 'カレールー', amount: 4, unit: '片' },
      { ingredientId: 'rice', name: 'ごはん', amount: 4, unit: '膳分' },
    ],
    steps: [
      '鶏肉と野菜を一口大に切る。',
      '鍋で玉ねぎをきつね色になるまで炒め、鶏肉・野菜を加えて炒める。',
      '水900mlを加えて沸騰したらアクを取り、蓋をして15分煮る。',
      '火を止めてカレールーを加えて溶かし、さらに10分煮てごはんに盛れば完成。',
    ],
    imageId: '1574071318508-1cdbab80d002',
  },
  {
    id: 'stew',
    name: 'クリームシチュー',
    category: '洋食',
    cookingTime: 40,
    baseServings: 4,
    mainIngredients: ['chicken-thigh', 'potato', 'onion', 'carrot', 'milk'],
    ingredients: [
      { ingredientId: 'chicken-thigh', name: '鶏もも肉', amount: 300, unit: 'g' },
      { ingredientId: 'potato', name: 'じゃがいも', amount: 3, unit: '個' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 1, unit: '個' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 1, unit: '本' },
      { ingredientId: 'milk', name: '牛乳', amount: 400, unit: 'ml' },
      { ingredientId: 'butter', name: 'バター', amount: 20, unit: 'g' },
      { ingredientId: 'flour', name: '小麦粉', amount: 3, unit: '大さじ' },
      { ingredientId: 'consomme', name: 'コンソメ', amount: 2, unit: '個' },
    ],
    steps: [
      '材料を一口大に切る。鍋でバターを熱し野菜と鶏肉を炒める。',
      '小麦粉をふり入れて炒め、水600mlとコンソメを加えて15分煮る。',
      '牛乳を加えてさらに5分煮て、塩こしょうで味を整えれば完成。',
    ],
    imageId: '1525059696034-4967a8e1dca2',
  },
  {
    id: 'napolitan',
    name: 'ナポリタン',
    category: '洋食',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['pasta', 'onion', 'green-pepper', 'ham', 'ketchup'],
    ingredients: [
      { ingredientId: 'pasta', name: 'パスタ', amount: 200, unit: 'g' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 1, unit: '個' },
      { ingredientId: 'green-pepper', name: 'ピーマン', amount: 2, unit: '個' },
      { ingredientId: 'ham', name: 'ハム', amount: 4, unit: '枚' },
      { ingredientId: 'ketchup', name: 'ケチャップ', amount: 5, unit: '大さじ' },
      { ingredientId: 'butter', name: 'バター', amount: 10, unit: 'g' },
    ],
    steps: [
      'パスタを袋の表示通りに茹でる。野菜・ハムを細切りにする。',
      'フライパンにバターを熱し、玉ねぎ・ピーマン・ハムを炒める。',
      'ケチャップを加えて炒め、茹でたパスタを加えて混ぜれば完成。',
    ],
    imageId: '1455619452474-d2be8b1e70cd',
  },
  {
    id: 'omuraisu',
    name: 'オムライス',
    category: '洋食',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['egg', 'rice', 'chicken-thigh', 'onion', 'ketchup'],
    ingredients: [
      { ingredientId: 'egg', name: '卵', amount: 4, unit: '個' },
      { ingredientId: 'rice', name: 'ごはん', amount: 2, unit: '膳分' },
      { ingredientId: 'chicken-thigh', name: '鶏もも肉', amount: 100, unit: 'g' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 0.5, unit: '個' },
      { ingredientId: 'ketchup', name: 'ケチャップ', amount: 4, unit: '大さじ' },
      { ingredientId: 'butter', name: 'バター', amount: 15, unit: 'g' },
    ],
    steps: [
      '鶏肉・玉ねぎをみじん切りにして炒め、ごはんとケチャップを加えてチキンライスを作る。',
      '卵2個を溶き、薄焼き卵を作ってチキンライスを包む。',
      'ケチャップをかけて完成。',
    ],
    imageId: '1546069901-ba9599a7e63c',
  },
  {
    id: 'korokke',
    name: 'コロッケ',
    category: '洋食',
    cookingTime: 40,
    baseServings: 4,
    mainIngredients: ['potato', 'ground-mix', 'onion'],
    ingredients: [
      { ingredientId: 'potato', name: 'じゃがいも', amount: 4, unit: '個' },
      { ingredientId: 'ground-mix', name: '合挽き肉', amount: 150, unit: 'g' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 0.5, unit: '個' },
      { ingredientId: 'egg', name: '卵', amount: 1, unit: '個' },
      { ingredientId: 'breadcrumb', name: 'パン粉', amount: 50, unit: 'g' },
      { ingredientId: 'flour', name: '小麦粉', amount: 30, unit: 'g' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
    ],
    steps: [
      'じゃがいもを茹でてつぶし、炒めた肉・玉ねぎと混ぜ、塩こしょうで味付け。',
      '成形して小麦粉→溶き卵→パン粉の順に衣をつける。',
      '170℃の油でキツネ色になるまで揚げれば完成。',
    ],
    imageId: '1626200419199-391ae4be7a41',
  },
  {
    id: 'potato-salad',
    name: 'ポテトサラダ',
    category: '洋食',
    cookingTime: 25,
    baseServings: 4,
    mainIngredients: ['potato', 'mayonnaise', 'ham', 'cucumber'],
    ingredients: [
      { ingredientId: 'potato', name: 'じゃがいも', amount: 3, unit: '個' },
      { ingredientId: 'ham', name: 'ハム', amount: 3, unit: '枚' },
      { ingredientId: 'cucumber', name: 'きゅうり', amount: 1, unit: '本' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 0.25, unit: '個' },
      { ingredientId: 'mayonnaise', name: 'マヨネーズ', amount: 3, unit: '大さじ' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
    ],
    steps: [
      'じゃがいもを茹でてつぶす。',
      'きゅうり・玉ねぎを薄切りにして塩もみし、水気を絞る。ハムは短冊切りにする。',
      '全てを混ぜ合わせてマヨネーズ・塩こしょうで和えれば完成。',
    ],
    imageId: '1512621776951-a57141f2eefd',
  },
  {
    id: 'consomme-soup',
    name: 'コンソメスープ',
    category: '洋食',
    cookingTime: 20,
    baseServings: 4,
    mainIngredients: ['onion', 'carrot', 'cabbage', 'consomme'],
    ingredients: [
      { ingredientId: 'onion', name: '玉ねぎ', amount: 1, unit: '個' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 1, unit: '本' },
      { ingredientId: 'cabbage', name: 'キャベツ', amount: 200, unit: 'g' },
      { ingredientId: 'bacon', name: 'ベーコン', amount: 50, unit: 'g' },
      { ingredientId: 'consomme', name: 'コンソメ', amount: 2, unit: '個' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
    ],
    steps: [
      '野菜とベーコンを食べやすい大きさに切る。',
      '水900mlにコンソメを溶かし、全ての具材を入れて15分煮る。',
      '塩こしょうで味を整えれば完成。',
    ],
    imageId: '1525059696034-4967a8e1dca2',
  },
  {
    id: 'french-toast',
    name: 'フレンチトースト',
    category: '洋食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['bread', 'egg', 'milk'],
    ingredients: [
      { ingredientId: 'bread', name: '食パン', amount: 2, unit: '枚' },
      { ingredientId: 'egg', name: '卵', amount: 2, unit: '個' },
      { ingredientId: 'milk', name: '牛乳', amount: 100, unit: 'ml' },
      { ingredientId: 'butter', name: 'バター', amount: 15, unit: 'g' },
      { ingredientId: 'sugar', name: '砂糖', amount: 1, unit: '大さじ' },
    ],
    steps: [
      '卵・牛乳・砂糖を混ぜた液に食パンを30分浸す。',
      'フライパンにバターを熱し、両面をじっくり焼く。',
      'お好みでシロップやはちみつをかけて完成。',
    ],
    imageId: '1484723091739-30a097e8f929',
  },
  {
    id: 'chicken-nanban',
    name: 'チキン南蛮',
    category: '洋食',
    cookingTime: 30,
    baseServings: 2,
    mainIngredients: ['chicken-thigh', 'egg', 'mayonnaise'],
    ingredients: [
      { ingredientId: 'chicken-thigh', name: '鶏もも肉', amount: 300, unit: 'g' },
      { ingredientId: 'egg', name: '卵', amount: 2, unit: '個' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 0.5, unit: '個' },
      { ingredientId: 'mayonnaise', name: 'マヨネーズ', amount: 3, unit: '大さじ' },
      { ingredientId: 'flour', name: '小麦粉', amount: 3, unit: '大さじ' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 2, unit: '大さじ' },
      { ingredientId: 'vinegar', name: '酢', amount: 2, unit: '大さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 1, unit: '大さじ' },
    ],
    steps: [
      '鶏肉に塩こしょうして小麦粉をまぶし、溶き卵をつけて揚げる。',
      '醤油・酢・砂糖を合わせた南蛮酢に揚げたての鶏肉を浸す。',
      '玉ねぎのみじん切りをマヨネーズで和えたタルタルソースをかけて完成。',
    ],
    imageId: '1626200419199-391ae4be7a41',
  },
  {
    id: 'meat-pasta',
    name: 'ミートソースパスタ',
    category: '洋食',
    cookingTime: 30,
    baseServings: 2,
    mainIngredients: ['pasta', 'ground-mix', 'onion', 'tomato-can'],
    ingredients: [
      { ingredientId: 'pasta', name: 'パスタ', amount: 200, unit: 'g' },
      { ingredientId: 'ground-mix', name: '合挽き肉', amount: 200, unit: 'g' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 1, unit: '個' },
      { ingredientId: 'garlic', name: 'にんにく', amount: 1, unit: '片' },
      { ingredientId: 'tomato-can', name: 'トマト缶', amount: 1, unit: '缶' },
      { ingredientId: 'consomme', name: 'コンソメ', amount: 1, unit: '個' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
    ],
    steps: [
      'にんにくと玉ねぎをみじん切りにして炒め、合挽き肉を加えて炒める。',
      'トマト缶・コンソメを加えて20分煮込み、塩こしょうで味付け。',
      '茹でたパスタにかけて完成。',
    ],
    imageId: '1540189549336-e6e99c3679fe',
  },
  {
    id: 'gratin',
    name: 'グラタン',
    category: '洋食',
    cookingTime: 40,
    baseServings: 2,
    mainIngredients: ['chicken-thigh', 'onion', 'milk', 'cheese'],
    ingredients: [
      { ingredientId: 'chicken-thigh', name: '鶏もも肉', amount: 150, unit: 'g' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 0.5, unit: '個' },
      { ingredientId: 'milk', name: '牛乳', amount: 400, unit: 'ml' },
      { ingredientId: 'butter', name: 'バター', amount: 30, unit: 'g' },
      { ingredientId: 'flour', name: '小麦粉', amount: 30, unit: 'g' },
      { ingredientId: 'cheese', name: 'チーズ', amount: 50, unit: 'g' },
      { ingredientId: 'pasta', name: 'マカロニ', amount: 80, unit: 'g' },
      { ingredientId: 'consomme', name: 'コンソメ', amount: 1, unit: '個' },
    ],
    steps: [
      'マカロニを茹でる。鶏肉と玉ねぎを炒める。',
      'バターで小麦粉を炒め、牛乳を少しずつ加えてホワイトソースを作る。',
      '具材を合わせてグラタン皿に入れ、チーズをのせて200℃のオーブンで15分焼けば完成。',
    ],
    imageId: '1574071318508-1cdbab80d002',
  },
  {
    id: 'pork-sote',
    name: 'ポークソテー',
    category: '洋食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['pork-loin', 'butter'],
    ingredients: [
      { ingredientId: 'pork-loin', name: '豚ロース', amount: 200, unit: 'g' },
      { ingredientId: 'butter', name: 'バター', amount: 15, unit: 'g' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'worcester', name: 'ウスターソース', amount: 1, unit: '大さじ' },
      { ingredientId: 'lemon', name: 'レモン', amount: 0.5, unit: '個' },
    ],
    steps: [
      '豚ロースは筋切りをして塩こしょうする。',
      'フライパンにバターを熱し、両面を焼く。',
      '醤油・ウスターソースをかけ、レモンを添えて完成。',
    ],
    imageId: '1568901346375-23c9450c58cd',
  },
  {
    id: 'minestrone',
    name: 'ミネストローネ',
    category: '洋食',
    cookingTime: 30,
    baseServings: 4,
    mainIngredients: ['tomato-can', 'onion', 'carrot', 'cabbage', 'bacon'],
    ingredients: [
      { ingredientId: 'tomato-can', name: 'トマト缶', amount: 1, unit: '缶' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 1, unit: '個' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 1, unit: '本' },
      { ingredientId: 'cabbage', name: 'キャベツ', amount: 200, unit: 'g' },
      { ingredientId: 'bacon', name: 'ベーコン', amount: 50, unit: 'g' },
      { ingredientId: 'garlic', name: 'にんにく', amount: 1, unit: '片' },
      { ingredientId: 'consomme', name: 'コンソメ', amount: 2, unit: '個' },
    ],
    steps: [
      '野菜とベーコンを1cm角に切る。',
      '鍋でにんにく・ベーコン・野菜を炒め、水600ml・トマト缶・コンソメを加える。',
      '20分煮込み、塩こしょうで味を整えれば完成。',
    ],
    imageId: '1525059696034-4967a8e1dca2',
  },
  {
    id: 'scrambled-egg',
    name: 'スクランブルエッグ',
    category: '洋食',
    cookingTime: 5,
    baseServings: 2,
    mainIngredients: ['egg', 'butter', 'milk'],
    ingredients: [
      { ingredientId: 'egg', name: '卵', amount: 3, unit: '個' },
      { ingredientId: 'butter', name: 'バター', amount: 10, unit: 'g' },
      { ingredientId: 'milk', name: '牛乳', amount: 30, unit: 'ml' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
    ],
    steps: [
      '卵・牛乳・塩こしょうを混ぜる。',
      'フライパンにバターを溶かし、卵液を入れて弱火でゆっくりかき混ぜる。',
      '半熟になったら火を止めて器に盛れば完成。',
    ],
    imageId: '1482049016688-2d3e1b311543',
  },
  {
    id: 'bacon-egg',
    name: 'ベーコンエッグ',
    category: '洋食',
    cookingTime: 10,
    baseServings: 2,
    mainIngredients: ['egg', 'bacon'],
    ingredients: [
      { ingredientId: 'egg', name: '卵', amount: 2, unit: '個' },
      { ingredientId: 'bacon', name: 'ベーコン', amount: 4, unit: '枚' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.3, unit: '小さじ' },
    ],
    steps: [
      'フライパンを熱し、ベーコンを焼く。',
      '端に寄せて卵を割り入れ、好みの硬さに焼けば完成。',
    ],
    imageId: '1482049016688-2d3e1b311543',
  },
  {
    id: 'yasai-itame',
    name: '野菜炒め',
    category: '洋食',
    cookingTime: 10,
    baseServings: 2,
    mainIngredients: ['cabbage', 'carrot', 'onion'],
    ingredients: [
      { ingredientId: 'cabbage', name: 'キャベツ', amount: 200, unit: 'g' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 0.5, unit: '本' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 0.5, unit: '個' },
      { ingredientId: 'pork-belly', name: '豚バラ肉', amount: 100, unit: 'g' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
      { ingredientId: 'oyster-sauce', name: 'オイスターソース', amount: 1, unit: '大さじ' },
    ],
    steps: [
      '野菜は食べやすい大きさに切る。',
      'フライパンを強火で熱し、豚肉を炒め、野菜を加えて炒める。',
      '醤油・塩こしょう・オイスターソースで味付けして完成。',
    ],
    imageId: '1512621776951-a57141f2eefd',
  },
  {
    id: 'garlic-shrimp',
    name: 'ガーリックシュリンプ',
    category: '洋食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['shrimp', 'garlic', 'butter'],
    ingredients: [
      { ingredientId: 'shrimp', name: 'エビ', amount: 200, unit: 'g' },
      { ingredientId: 'garlic', name: 'にんにく', amount: 2, unit: '片' },
      { ingredientId: 'butter', name: 'バター', amount: 20, unit: 'g' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'lemon', name: 'レモン', amount: 0.5, unit: '個' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
    ],
    steps: [
      'エビは殻をむき、背わたを取る。にんにくはみじん切りにする。',
      'フライパンにバターを溶かし、にんにくを香りが出るまで炒める。',
      'エビを加えて炒め、醤油・塩こしょうで味付け。レモンを絞れば完成。',
    ],
    imageId: '1504674900247-0877df9cc836',
  },
  {
    id: 'salmon-meuniere',
    name: 'サーモンのムニエル',
    category: '洋食',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['salmon', 'butter', 'lemon'],
    ingredients: [
      { ingredientId: 'salmon', name: '鮭', amount: 2, unit: '切れ' },
      { ingredientId: 'butter', name: 'バター', amount: 20, unit: 'g' },
      { ingredientId: 'flour', name: '小麦粉', amount: 2, unit: '大さじ' },
      { ingredientId: 'lemon', name: 'レモン', amount: 1, unit: '個' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
    ],
    steps: [
      '鮭に塩こしょうをして小麦粉をまぶす。',
      'フライパンにバターを溶かし、中火で両面を焼く。',
      'レモンを絞りかけて完成。',
    ],
    imageId: '1467003909585-2f8a72700288',
  },

  // ===== 中華 =====
  {
    id: 'mapo-tofu',
    name: '麻婆豆腐',
    category: '中華',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['tofu', 'ground-pork', 'negi', 'mapo-tofu-sauce'],
    ingredients: [
      { ingredientId: 'tofu', name: '木綿豆腐', amount: 1, unit: '丁' },
      { ingredientId: 'ground-pork', name: '豚ひき肉', amount: 100, unit: 'g' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 0.5, unit: '本' },
      { ingredientId: 'garlic', name: 'にんにく', amount: 1, unit: '片' },
      { ingredientId: 'ginger', name: '生姜', amount: 1, unit: '片' },
      { ingredientId: 'mapo-tofu-sauce', name: '豆板醤', amount: 1, unit: '小さじ' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'chicken-stock', name: '鶏がらスープの素', amount: 1, unit: '小さじ' },
      { ingredientId: 'starch', name: '片栗粉', amount: 1, unit: '大さじ' },
    ],
    steps: [
      'にんにく・生姜・ねぎをみじん切りにする。豆腐は2cm角に切る。',
      'フライパンで豚肉・豆板醤・にんにく・生姜を炒める。',
      '水200ml・鶏がらスープ・醤油を加え、豆腐を入れて煮る。水溶き片栗粉でとろみをつけ、ごま油・ねぎを加えて完成。',
    ],
    imageId: '1601050690597-df0568f70950',
  },
  {
    id: 'gyoza',
    name: '餃子',
    category: '中華',
    cookingTime: 30,
    baseServings: 2,
    mainIngredients: ['ground-pork', 'cabbage', 'gyoza-skin'],
    ingredients: [
      { ingredientId: 'ground-pork', name: '豚ひき肉', amount: 200, unit: 'g' },
      { ingredientId: 'cabbage', name: 'キャベツ', amount: 200, unit: 'g' },
      { ingredientId: 'gyoza-skin', name: '餃子の皮', amount: 20, unit: '枚' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 0.3, unit: '本' },
      { ingredientId: 'ginger', name: '生姜', amount: 1, unit: '片' },
      { ingredientId: 'garlic', name: 'にんにく', amount: 1, unit: '片' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 1, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
    ],
    steps: [
      'キャベツは塩もみして水気を絞り、みじん切りにする。',
      '豚ひき肉・キャベツ・みじん切りのねぎ・生姜・にんにく・調味料を混ぜる。',
      '皮に包んで成形する。フライパンに並べて焼き色をつけ、水を加えて蓋をして蒸し焼きにする。水が蒸発したらごま油を加えてパリッと仕上げれば完成。',
    ],
    imageId: '1574484284002-952d92456975',
  },
  {
    id: 'kaiko-niku',
    name: '回鍋肉',
    category: '中華',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['pork-belly', 'cabbage', 'green-pepper', 'tenmen-sauce'],
    ingredients: [
      { ingredientId: 'pork-belly', name: '豚バラ肉', amount: 200, unit: 'g' },
      { ingredientId: 'cabbage', name: 'キャベツ', amount: 200, unit: 'g' },
      { ingredientId: 'green-pepper', name: 'ピーマン', amount: 2, unit: '個' },
      { ingredientId: 'garlic', name: 'にんにく', amount: 1, unit: '片' },
      { ingredientId: 'ginger', name: '生姜', amount: 1, unit: '片' },
      { ingredientId: 'tenmen-sauce', name: '甜麺醤', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 1, unit: '大さじ' },
    ],
    steps: [
      '豚肉は3cm幅に切る。キャベツはざく切り、ピーマンは乱切りにする。',
      '豚肉を炒め、キャベツ・ピーマンを加えてさらに炒める。',
      '甜麺醤・醤油・酒を加えて絡めれば完成。',
    ],
    imageId: '1567620832903-9fc6debc209f',
  },
  {
    id: 'chinjaosusi',
    name: '青椒肉絲',
    category: '中華',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['pork-loin', 'green-pepper', 'bamboo'],
    ingredients: [
      { ingredientId: 'pork-loin', name: '豚ロース（薄切り）', amount: 150, unit: 'g' },
      { ingredientId: 'green-pepper', name: 'ピーマン', amount: 4, unit: '個' },
      { ingredientId: 'bamboo', name: 'タケノコ（水煮）', amount: 100, unit: 'g' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'sake', name: '料理酒', amount: 1, unit: '大さじ' },
      { ingredientId: 'oyster-sauce', name: 'オイスターソース', amount: 1, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'starch', name: '片栗粉', amount: 1, unit: '大さじ' },
    ],
    steps: [
      '豚肉・ピーマン・タケノコをすべて細切りにする。豚肉は片栗粉・醤油・酒で下味をつける。',
      'フライパンで豚肉を炒め、野菜を加えてさらに炒める。',
      'オイスターソース・醤油で味付けし、ごま油を回しかければ完成。',
    ],
    imageId: '1565557623262-b51c2513a641',
  },
  {
    id: 'ebichiri',
    name: 'エビチリ',
    category: '中華',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['shrimp', 'ketchup', 'negi', 'garlic'],
    ingredients: [
      { ingredientId: 'shrimp', name: 'エビ', amount: 200, unit: 'g' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 0.5, unit: '本' },
      { ingredientId: 'garlic', name: 'にんにく', amount: 1, unit: '片' },
      { ingredientId: 'ginger', name: '生姜', amount: 1, unit: '片' },
      { ingredientId: 'ketchup', name: 'ケチャップ', amount: 3, unit: '大さじ' },
      { ingredientId: 'mapo-tofu-sauce', name: '豆板醤', amount: 0.5, unit: '小さじ' },
      { ingredientId: 'chicken-stock', name: '鶏がらスープの素', amount: 1, unit: '小さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'starch', name: '片栗粉', amount: 1, unit: '大さじ' },
    ],
    steps: [
      'エビは殻をむき、背わたを取って片栗粉で揉み洗いする。',
      'みじん切りのにんにく・生姜・豆板醤を炒め、ケチャップ・鶏がらスープ・水150mlを加える。',
      'エビを加えて炒め、水溶き片栗粉でとろみをつけ、ねぎとごま油で仕上げれば完成。',
    ],
    imageId: '1534482421-64566f976cfa',
  },
  {
    id: 'happosai',
    name: '八宝菜',
    category: '中華',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['pork-belly', 'shrimp', 'chinese-cabbage', 'carrot'],
    ingredients: [
      { ingredientId: 'pork-belly', name: '豚バラ肉', amount: 100, unit: 'g' },
      { ingredientId: 'shrimp', name: 'エビ', amount: 100, unit: 'g' },
      { ingredientId: 'chinese-cabbage', name: '白菜', amount: 200, unit: 'g' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 0.5, unit: '本' },
      { ingredientId: 'mushroom', name: 'しいたけ', amount: 3, unit: '個' },
      { ingredientId: 'bamboo', name: 'タケノコ（水煮）', amount: 50, unit: 'g' },
      { ingredientId: 'oyster-sauce', name: 'オイスターソース', amount: 2, unit: '大さじ' },
      { ingredientId: 'chicken-stock', name: '鶏がらスープの素', amount: 1, unit: '小さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'starch', name: '片栗粉', amount: 1.5, unit: '大さじ' },
    ],
    steps: [
      '全ての食材を食べやすい大きさに切る。',
      '豚肉・エビを炒め、野菜を加えてさらに炒める。',
      '水200ml・オイスターソース・鶏がらスープを加えて煮立て、水溶き片栗粉でとろみをつけ、ごま油で仕上げれば完成。',
    ],
    imageId: '1512621776951-a57141f2eefd',
  },
  {
    id: 'banbanjii',
    name: 'バンバンジー',
    category: '中華',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['chicken-breast', 'cucumber'],
    ingredients: [
      { ingredientId: 'chicken-breast', name: '鶏むね肉', amount: 1, unit: '枚' },
      { ingredientId: 'cucumber', name: 'きゅうり', amount: 1, unit: '本' },
      { ingredientId: 'sesame', name: 'すりごま', amount: 2, unit: '大さじ' },
      { ingredientId: 'mayonnaise', name: 'マヨネーズ', amount: 2, unit: '大さじ' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'vinegar', name: '酢', amount: 1, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 1, unit: '小さじ' },
    ],
    steps: [
      '鶏むね肉を茹でてしっかり冷まし、手で割いて細くする。',
      'きゅうりは千切りにする。',
      'すりごま・マヨネーズ・醤油・酢・ごま油・砂糖を混ぜてたれを作り、鶏肉ときゅうりにかければ完成。',
    ],
    imageId: '1546069901-ba9599a7e63c',
  },
  {
    id: 'chuuka-soup',
    name: '中華スープ',
    category: '中華',
    cookingTime: 10,
    baseServings: 2,
    mainIngredients: ['egg', 'negi', 'chicken-stock'],
    ingredients: [
      { ingredientId: 'egg', name: '卵', amount: 2, unit: '個' },
      { ingredientId: 'negi', name: '長ねぎ', amount: 0.3, unit: '本' },
      { ingredientId: 'chicken-stock', name: '鶏がらスープの素', amount: 2, unit: '小さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'starch', name: '片栗粉', amount: 1, unit: '大さじ' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.3, unit: '小さじ' },
    ],
    steps: [
      '水400mlを沸かし、鶏がらスープの素を溶かす。',
      '水溶き片栗粉でとろみをつけ、溶き卵を細く流し入れる。',
      '塩こしょう・ごま油で味を整え、ねぎを散らせば完成。',
    ],
    imageId: '1525059696034-4967a8e1dca2',
  },
  {
    id: 'subuta',
    name: '酢豚',
    category: '中華',
    cookingTime: 30,
    baseServings: 2,
    mainIngredients: ['pork-belly', 'green-pepper', 'onion', 'carrot'],
    ingredients: [
      { ingredientId: 'pork-belly', name: '豚バラ肉', amount: 200, unit: 'g' },
      { ingredientId: 'green-pepper', name: 'ピーマン', amount: 2, unit: '個' },
      { ingredientId: 'onion', name: '玉ねぎ', amount: 0.5, unit: '個' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 0.5, unit: '本' },
      { ingredientId: 'ketchup', name: 'ケチャップ', amount: 3, unit: '大さじ' },
      { ingredientId: 'vinegar', name: '酢', amount: 2, unit: '大さじ' },
      { ingredientId: 'sugar', name: '砂糖', amount: 2, unit: '大さじ' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'starch', name: '片栗粉', amount: 3, unit: '大さじ' },
    ],
    steps: [
      '豚肉を一口大に切り、塩こしょう・片栗粉をまぶして揚げる。',
      '野菜を炒め、ケチャップ・酢・砂糖・醤油・水を合わせたソースを加える。',
      '揚げた豚肉を加えて絡めれば完成。',
    ],
    imageId: '1603360946369-dc9bb6258143',
  },
  {
    id: 'nira-tama',
    name: 'ニラ玉炒め',
    category: '中華',
    cookingTime: 10,
    baseServings: 2,
    mainIngredients: ['nira', 'egg'],
    ingredients: [
      { ingredientId: 'nira', name: 'ニラ', amount: 1, unit: '束' },
      { ingredientId: 'egg', name: '卵', amount: 3, unit: '個' },
      { ingredientId: 'chicken-stock', name: '鶏がらスープの素', amount: 0.5, unit: '小さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
    ],
    steps: [
      'ニラは4cm幅に切る。卵を溶いて塩こしょうする。',
      'フライパンに油を熱し、卵を半熟に炒めて取り出す。',
      'フライパンでニラを炒め、卵を戻し入れ、鶏がらスープ・ごま油で味付ければ完成。',
    ],
    imageId: '1482049016688-2d3e1b311543',
  },
  {
    id: 'moyashi-itame',
    name: 'もやし炒め',
    category: '中華',
    cookingTime: 10,
    baseServings: 2,
    mainIngredients: ['moyashi', 'pork-belly'],
    ingredients: [
      { ingredientId: 'moyashi', name: 'もやし', amount: 200, unit: 'g' },
      { ingredientId: 'pork-belly', name: '豚バラ肉', amount: 100, unit: 'g' },
      { ingredientId: 'nira', name: 'ニラ', amount: 0.5, unit: '束' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'oyster-sauce', name: 'オイスターソース', amount: 1, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.3, unit: '小さじ' },
    ],
    steps: [
      '豚肉は食べやすい大きさに切る。',
      'フライパンで豚肉を炒め、もやし・ニラを加えて強火で炒める。',
      '醤油・オイスターソース・塩こしょう・ごま油で味付ければ完成。',
    ],
    imageId: '1567620832903-9fc6debc209f',
  },
  {
    id: 'harumaki',
    name: '春巻き',
    category: '中華',
    cookingTime: 30,
    baseServings: 2,
    mainIngredients: ['ground-pork', 'chinese-cabbage', 'harumaki-skin'],
    ingredients: [
      { ingredientId: 'ground-pork', name: '豚ひき肉', amount: 150, unit: 'g' },
      { ingredientId: 'chinese-cabbage', name: '白菜', amount: 200, unit: 'g' },
      { ingredientId: 'harumaki-skin', name: '春巻きの皮', amount: 8, unit: '枚' },
      { ingredientId: 'mushroom', name: 'しいたけ', amount: 2, unit: '個' },
      { ingredientId: 'oyster-sauce', name: 'オイスターソース', amount: 1.5, unit: '大さじ' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'starch', name: '片栗粉', amount: 1, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
    ],
    steps: [
      '白菜・しいたけを細切りにして炒め、豚ひき肉と一緒に調味料で味付けして冷ます。',
      '春巻きの皮で具材を包む。',
      '170℃の油でキツネ色になるまで揚げれば完成。',
    ],
    imageId: '1574484284002-952d92456975',
  },
  {
    id: 'yakisoba',
    name: '焼きそば',
    category: '中華',
    cookingTime: 15,
    baseServings: 2,
    mainIngredients: ['chinese-noodle', 'pork-belly', 'cabbage', 'moyashi'],
    ingredients: [
      { ingredientId: 'chinese-noodle', name: '中華麺', amount: 2, unit: '玉' },
      { ingredientId: 'pork-belly', name: '豚バラ肉', amount: 150, unit: 'g' },
      { ingredientId: 'cabbage', name: 'キャベツ', amount: 200, unit: 'g' },
      { ingredientId: 'moyashi', name: 'もやし', amount: 100, unit: 'g' },
      { ingredientId: 'worcester', name: 'ウスターソース', amount: 2, unit: '大さじ' },
      { ingredientId: 'oyster-sauce', name: 'オイスターソース', amount: 1, unit: '大さじ' },
      { ingredientId: 'soy-sauce', name: '醤油', amount: 1, unit: '大さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
    ],
    steps: [
      '豚肉・キャベツを食べやすい大きさに切る。',
      'フライパンで豚肉・野菜を炒め、麺を加えて炒める。',
      'ウスターソース・オイスターソース・醤油で味付けし、ごま油で仕上げれば完成。',
    ],
    imageId: '1569050467447-ce54b3bbc37d',
  },
  {
    id: 'tanmen',
    name: 'タンメン',
    category: '中華',
    cookingTime: 20,
    baseServings: 2,
    mainIngredients: ['chinese-noodle', 'pork-belly', 'chinese-cabbage', 'carrot', 'moyashi'],
    ingredients: [
      { ingredientId: 'chinese-noodle', name: '中華麺', amount: 2, unit: '玉' },
      { ingredientId: 'pork-belly', name: '豚バラ肉', amount: 100, unit: 'g' },
      { ingredientId: 'chinese-cabbage', name: '白菜', amount: 200, unit: 'g' },
      { ingredientId: 'carrot', name: 'にんじん', amount: 0.5, unit: '本' },
      { ingredientId: 'moyashi', name: 'もやし', amount: 100, unit: 'g' },
      { ingredientId: 'chicken-stock', name: '鶏がらスープの素', amount: 2, unit: '小さじ' },
      { ingredientId: 'sesame-oil', name: 'ごま油', amount: 1, unit: '小さじ' },
      { ingredientId: 'salt', name: '塩こしょう', amount: 0.5, unit: '小さじ' },
    ],
    steps: [
      '野菜と豚肉を炒め、水600mlと鶏がらスープを加えて5分煮る。塩こしょうで味付け。',
      '別鍋で中華麺を茹でる。',
      '器に麺を盛り、スープと野菜をかけ、ごま油を垂らして完成。',
    ],
    imageId: '1569050467447-ce54b3bbc37d',
  },
]
